export enum SortNameField {
    ID = "id",
    NAME = "name",
    COORDINATES_ID = "coordinatesId",
    COORDINATES_X = "coordinatesX",
    COORDINATES_Y = "coordinatesY",
    CREATION_DATE = "creationDate",
    AREA = "area",
    NUMBER_OF_ROOMS = "numberOfRooms",
    HEIGHT = "height",
    VIEW = "view",
    TRANSPORT = "transport",
    HOUSE_ID = "houseId",
    HOUSE_NAME = "houseName",
    HOUSE_YEAR = "houseYear",
    HOUSE_NUMBER_OF_FLATS_ON_FLOOR = "houseNumberOfFlatsOnFloor",
    PRICE = "price",
    BALCONY_TYPE = "balconyType",
    WALKING_MINUTES_TO_METRO = "walkingMinutesToMetro",
    TRANSPORT_MINUTES_TO_METRO = "transportMinutesToMetro",
}

export const SortNameFieldDictionary: Record<string, string> = {
    [SortNameField.ID]: "Id",
    [SortNameField.NAME]: "Name",
    [SortNameField.COORDINATES_ID]: "Coordinates id",
    [SortNameField.COORDINATES_X]: "Coordinates x",
    [SortNameField.COORDINATES_Y]: "Coordinates y",
    [SortNameField.CREATION_DATE]: "Creation date",
    [SortNameField.AREA]: "Area",
    [SortNameField.NUMBER_OF_ROOMS]: "Number of rooms",
    [SortNameField.HEIGHT]: "Height",
    [SortNameField.VIEW]: "View",
    [SortNameField.TRANSPORT]: "Transport",
    [SortNameField.HOUSE_ID]: "House id",
    [SortNameField.HOUSE_NAME]: "House name",
    [SortNameField.HOUSE_YEAR]: "House year",
    [SortNameField.HOUSE_NUMBER_OF_FLATS_ON_FLOOR]: "House number of flats on floor",
    [SortNameField.PRICE]: "Price",
    [SortNameField.BALCONY_TYPE]: "Balcony type",
    [SortNameField.WALKING_MINUTES_TO_METRO]: "Walking minutes to metro",
    [SortNameField.TRANSPORT_MINUTES_TO_METRO]: "Transport minutes to metro",
};
