export enum SortNameField {
    ID = "id",
    NAME = "name",
    COORDINATES_ID = "coordinatesId",
    COORDINATES_X = "coordinatesX",
    COORDINATES_Y = "coordinatesY",
    CREATION_DATE = "creationDate",
    AREA = "area",
    NUMBER_OF_ROOMS = "numberOfRooms",
    HEIGHT = "height",
    VIEW = "view",
    TRANSPORT = "transport",
    HOUSE_ID = "houseId",
    HOUSE_NAME = "houseName",
    HOUSE_YEAR = "houseYear",
    HOUSE_NUMBER_OF_FLATS_ON_FLOOR = "houseNumberOfFlatsOnFloor",
}

export const SortNameFieldDictionary: Record<string, string> = {
    ID: "Id",
    NAME: "Name",
    COORDINATES_ID: "Coordinates id",
    COORDINATES_X: "Coordinates x",
    COORDINATES_Y: "Coordinates y",
    CREATION_DATE: "Creation date",
    AREA: "Area",
    NUMBER_OF_ROOMS: "Number of rooms",
    HEIGHT: "Height",
    VIEW: "View",
    TRANSPORT: "Transport",
    HOUSE_ID: "House id",
    HOUSE_NAME: "House name",
    HOUSE_YEAR: "House year",
    HOUSE_NUMBER_OF_FLATS_ON_FLOOR: "House number of flats on floor",
};
